INSERT INTO destinies (state, bestseason, weather, description, imageurl) VALUES
('Acre', 'Junho a Setembro', 'O clima é tropical úmido, com alta umidade durante todo o ano. As temperaturas variam entre 24°C e 36°C.', 'O Acre é um estado localizado na região Norte do Brasil, conhecido por suas reservas naturais e pela cultura indígena.', 'url_imagem_acre.jpg'),
('Alagoas', 'Maio a Setembro', 'O clima é tropical úmido, com temperaturas elevadas e chuvas frequentes. A temperatura média varia entre 24°C e 32°C.', 'Alagoas é um estado costeiro do Nordeste brasileiro, conhecido por suas belas praias e rica cultura.', 'url_imagem_alagoas.jpg'),
('Amapá', 'Junho a Setembro', 'O clima é equatorial, com temperaturas elevadas e chuvas frequentes ao longo do ano. A média de temperatura varia entre 25°C e 31°C.', 'O Amapá é um estado na região Norte do Brasil, conhecido por sua diversidade cultural e belezas naturais, como a Floresta Amazônica.', 'url_imagem_amapa.jpg'),
('Amazonas', 'Junho a Setembro', 'O clima é equatorial, com altas temperaturas e chuvas frequentes. A média de temperatura varia entre 24°C e 32°C.', 'O Amazonas é o maior estado brasileiro, localizado na região Norte. É conhecido por sua rica biodiversidade e pela Floresta Amazônica.', 'url_imagem_amazonas.jpg'),
('Bahia', 'Abril a Outubro', 'O clima é tropical, com temperaturas elevadas e chuvas concentradas no verão. A temperatura média varia entre 24°C e 30°C.', 'A Bahia é um estado no Nordeste brasileiro, famoso por suas praias paradisíacas, culinária típica e cultura diversificada.', 'url_imagem_bahia.jpg'),
('Ceará', 'Julho a Dezembro', 'O clima é tropical, com temperaturas elevadas e chuvas concentradas no primeiro semestre. A temperatura média varia entre 26°C e 32°C.', 'O Ceará é um estado no Nordeste brasileiro, conhecido por suas belas praias, dunas e pela cidade de Fortaleza.', 'url_imagem_ceara.jpg'),
('Distrito Federal', 'Abril a Setembro', 'O clima é tropical de altitude, com temperaturas mais amenas que outras regiões do Brasil. A média de temperatura varia entre 15°C e 28°C.', 'O Distrito Federal é a capital do Brasil, onde se encontra Brasília, conhecida por sua arquitetura moderna e urbanismo planejado.', 'url_imagem_distrito_federal.jpg'),
('Espírito Santo', 'Maio a Setembro', 'O clima é tropical, com temperaturas elevadas e chuvas concentradas no verão. A temperatura média varia entre 22°C e 30°C.', 'O Espírito Santo é um estado no Sudeste brasileiro, famoso por suas praias, montanhas e pelo Convento da Penha.', 'url_imagem_espirito_santo.jpg'),
('Goiás', 'Maio a Setembro', 'O clima é tropical, com temperaturas elevadas e chuvas concentradas no verão. A temperatura média varia entre 20°C e 30°C.', 'Goiás é um estado localizado na região Centro-Oeste do Brasil, conhecido por suas cidades históricas, como Pirenópolis e Goiás Velho.', 'url_imagem_goias.jpg'),
('Maranhão', 'Junho a Setembro', 'O clima é tropical, com altas temperaturas e chuvas frequentes. A média de temperatura varia entre 25°C e 32°C.', 'O Maranhão é um estado no Nordeste brasileiro, conhecido por suas praias, pelos Lençóis Maranhenses e pela cidade de São Luís, Patrimônio Mundial da UNESCO.', 'url_imagem_maranhao.jpg'),
('Mato Grosso', 'Maio a Setembro', 'O clima é tropical, com temperaturas elevadas e chuvas concentradas no verão. A temperatura média varia entre 22°C e 32°C.', 'Mato Grosso é um estado na região Centro-Oeste do Brasil, conhecido por sua biodiversidade, pelo Pantanal e pela Chapada dos Guimarães.', 'url_imagem_mato_grosso.jpg'),
('Mato Grosso do Sul', 'Maio a Setembro', 'O clima é tropical, com temperaturas elevadas e chuvas concentradas no verão. A temperatura média varia entre 22°C e 31°C.', 'Mato Grosso do Sul é um estado na região Centro-Oeste do Brasil, conhecido pelo Pantanal, pelo turismo de aventura e pelas belezas naturais.', 'url_imagem_mato_grosso_do_sul.jpg'),
('Minas Gerais', 'Maio a Setembro', 'O clima é tropical de altitude, com temperaturas mais amenas que outras regiões do Brasil. A média de temperatura varia entre 15°C e 28°C.', 'Minas Gerais é um estado no Sudeste brasileiro, conhecido por suas cidades históricas, como Ouro Preto, e por suas montanhas e cachoeiras.', 'url_imagem_minas_gerais.jpg'),
('Pará', 'Junho a Setembro', 'O clima é equatorial, com altas temperaturas e chuvas frequentes. A média de temperatura varia entre 24°C e 32°C.', 'O Pará é um estado na região Norte do Brasil, conhecido pela Amazônia, pelas ilhas e praias, e pela culinária regional.', 'url_imagem_para.jpg')





